version: 2
jobs:
  build:
    docker:
      - image: vivekanandjain/ns3ubuntu:16.04

    steps:
      - checkout
      - run:
          name: Configure and Install ns-3
          command: |
            ls
            mkdir /home/ns-3-dev-git
            ./waf configure --enable-tests --enable-examples
            ./waf -j2
